require("config.onedark")

require("config.bufferline")
require("config.cmp")
require("config.comment")
require("config.gitsigns")
require("config.guess-indent")
require("config.lsp_signature")
require("config.lualine")
require("config.nvim-lsp")
require("config.nvim-tree")
require("config.nvim-treesitter")
require("config.trim")
